os.system("cls")
# PASSO 1 - DECLARAR AS VARIAVEIS

print('Exemplo 01 - Projeto Soma')
nome_usuario = input ("Entre com seu nome:")
valor01 = int(input("Entre com o primeiro valor:"))
valor02 = int(input("Entre com o segundo valor:"))

# PASSO 2 - PROCESSAMENTO - CALCULOS
total = valor01+valor02

# PASSO 3 - EXIBIR A SAIDA - RESULTADO
print("Nome do Usuario:", nome_usuario)
print ("O total é:", total)
input("Pressione a tecla <Enter> para finalizar")